FROM ghcr.io/simonai-git/swarmit-base:latest
RUN npm install -g typescript eslint prettier \
    @typescript-eslint/parser @typescript-eslint/eslint-plugin \
    depcheck madge
ENV NODE_ENV=development
